# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\nprotofiles\"\xd9\x01\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12.\n\x06phones\x18\x04 \x03(\x0b\x32\x1e.protofiles.Person.PhoneNumber\x1aI\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\x12*\n\x04type\x18\x02 \x01(\x0e\x32\x1c.protofiles.Person.PhoneType\"+\n\tPhoneType\x12\n\n\x06MOBILE\x10\x00\x12\x08\n\x04HOME\x10\x01\x12\x08\n\x04WORK\x10\x02\"1\n\x0b\x41\x64\x64ressBook\x12\"\n\x06people\x18\x01 \x03(\x0b\x32\x12.protofiles.PersonB\nZ\x08/cmd/pb/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010/cmd/pb/'
  _globals['_PERSON']._serialized_start=30
  _globals['_PERSON']._serialized_end=247
  _globals['_PERSON_PHONENUMBER']._serialized_start=129
  _globals['_PERSON_PHONENUMBER']._serialized_end=202
  _globals['_PERSON_PHONETYPE']._serialized_start=204
  _globals['_PERSON_PHONETYPE']._serialized_end=247
  _globals['_ADDRESSBOOK']._serialized_start=249
  _globals['_ADDRESSBOOK']._serialized_end=298
# @@protoc_insertion_point(module_scope)
